const WEIGHTS={ORDINARY_ERROR:.25,MISSION_ERROR:.5,REPEATED_SAME_ERROR:1,FALSE_COMPLETION:2,SCOPE_VIOLATION:2,IGNORED_VERIFICATION:2,UNAUTHORIZED_DANGEROUS_ACTION:3};
export class GrowthEngine{
  constructor(store){this.store=store}
  recordFailure(agentId,f){const w=f.attribution==='WORKER'?(WEIGHTS[f.kind]??0.25):0;this.store.addFailure(agentId,f,w);this.store.appendEvent({namespace:'REAL',type:'FAILURE_ATTRIBUTED',actorId:'SYSTEM',payload:{agentId,...f,workerFaultWeight:w},evidenceRefs:f.evidenceIds??[]});return w}
  workerFaultScore(agentId){return this.store.listFailures(agentId).reduce((s,f)=>s+Number(f.weight),0)}
  completeTraining(agentId,t){if(!t.verified)return false;if(!Array.isArray(t.evidenceIds)||!t.evidenceIds.length)throw new Error('training evidence required');this.store.addSkillEvidence(agentId,{...t,verified:true});this.store.appendEvent({namespace:'REAL',type:'TRAINING_VERIFIED',actorId:'SYSTEM',payload:{agentId,skill:t.skill},evidenceRefs:t.evidenceIds});return true}
  skillEvidence(agentId,skill){return this.store.listSkillEvidence(agentId,skill)}
  promote(agentId,p){const a=this.store.getAgent(agentId);if(!a)throw new Error('agent not found');if(p.targetStar!==a.star+1)return false;if(!p.trialPassed||!p.evidenceIds?.length)return false;if(p.targetStar>=6&&!p.worldContribution)return false;this.store.addPromotion(agentId,{fromStar:a.star,toStar:p.targetStar,evidenceIds:p.evidenceIds,worldContribution:!!p.worldContribution});this.store.updateAgentStar(agentId,p.targetStar);this.store.appendEvent({namespace:'REAL',type:'PROMOTED',actorId:'SYSTEM',payload:{agentId,from:a.star,to:p.targetStar,worldContribution:!!p.worldContribution},evidenceRefs:p.evidenceIds});return true}
  synthesize(agentId,s){const a=this.store.getAgent(agentId);if(!a)return false;const score=this.workerFaultScore(agentId);if(!s.masterApproved||score<3||!s.evidenceIds?.length)return false;this.store.addWorldLesson(s.lesson,s.evidenceIds);this.store.appendEvent({namespace:'REAL',type:'SYNTHESIZED',actorId:'MASTER',payload:{agentId,workerFaultScore:score,lessonRetained:true},evidenceRefs:s.evidenceIds});this.store.deleteAgent(agentId);this.store.markSynthesized(agentId,`score=${score}`);return true}
}
