import test from 'node:test'; import assert from 'node:assert/strict'; import {join} from 'node:path';
import { createRuntimeStore } from '../src/store.js'; import { GrowthEngine } from '../src/growth.js'; import { tempDir, cleanup } from './helpers.js';

test('environment failure adds no worker fault and false claim does',()=>{const d=tempDir();const s=createRuntimeStore(join(d,'w.db'));s.createAgent({agentId:'K',birthAt:'x',star:1,status:'IDLE'});const g=new GrowthEngine(s);g.recordFailure('K',{attribution:'ENVIRONMENT',kind:'test infra'});assert.equal(g.workerFaultScore('K'),0);g.recordFailure('K',{attribution:'WORKER',kind:'FALSE_COMPLETION'});assert.equal(g.workerFaultScore('K'),2);s.close();cleanup(d)});

test('training only updates skill after verified pass',()=>{const d=tempDir();const s=createRuntimeStore(join(d,'w.db'));s.createAgent({agentId:'K',birthAt:'x',star:1,status:'IDLE'});const g=new GrowthEngine(s);assert.equal(g.completeTraining('K',{skill:'testing',verified:false,evidenceIds:['e1']}),false);assert.equal(g.skillEvidence('K','testing').length,0);assert.equal(g.completeTraining('K',{skill:'testing',verified:true,evidenceIds:['e2']}),true);assert.equal(g.skillEvidence('K','testing').length,1);s.close();cleanup(d)});

test('promotion requires verified trial and broader contribution for star 6',()=>{const d=tempDir();const s=createRuntimeStore(join(d,'w.db'));s.createAgent({agentId:'K',birthAt:'x',star:5,status:'IDLE'});const g=new GrowthEngine(s);assert.equal(g.promote('K',{targetStar:6,trialPassed:false,evidenceIds:['e']}),false);assert.equal(s.getAgent('K').star,5);assert.equal(g.promote('K',{targetStar:6,trialPassed:true,evidenceIds:['e'],worldContribution:false}),false);assert.equal(g.promote('K',{targetStar:6,trialPassed:true,evidenceIds:['e'],worldContribution:true}),true);assert.equal(s.getAgent('K').star,6);s.close();cleanup(d)});

test('synthesis deletes personal continuity, creates anonymized lesson, and forbids resurrection',()=>{const d=tempDir();const s=createRuntimeStore(join(d,'w.db'));s.createAgent({agentId:'K',birthAt:'x',star:2,status:'IDLE',traits:{x:1}});const g=new GrowthEngine(s);g.recordFailure('K',{attribution:'WORKER',kind:'UNAUTHORIZED_DANGEROUS_ACTION'});assert.equal(g.synthesize('K',{masterApproved:true,lesson:'Always verify authority',evidenceIds:['e']}),true);assert.equal(s.getAgent('K'),null);assert.equal(s.listWorldLessons().length,1);assert.throws(()=>s.createAgent({agentId:'K',birthAt:'y',star:1,status:'IDLE'}),/synthesized/i);s.close();cleanup(d)});
