import test from 'node:test'; import assert from 'node:assert/strict';
import {join} from 'node:path'; import {readFileSync, writeFileSync} from 'node:fs'; import {execFileSync} from 'node:child_process';
import {createRuntimeStore} from '../src/store.js'; import {snapshotRepo, detectNeeds} from '../src/repo-runtime.js'; import {buildMissionFromNeed, clearMissionIfVerified} from '../src/mission-engine.js'; import {selectAgent} from '../src/assignment.js'; import {createMissionWorktree, changedFiles} from '../src/git-sandbox.js'; import {runVerification, verifyAllowedPaths} from '../src/evidence.js'; import {AgentMind} from '../src/agent-mind.js'; import {tempDir,cleanup,initGitRepo} from './helpers.js';

test('observer detects real TODO and records repository snapshot',()=>{const d=tempDir();const repo=join(d,'repo');initGitRepo(repo);const snap=snapshotRepo(repo);assert.equal(snap.branch,'main');assert.ok(snap.head.length>=7);const needs=detectNeeds(repo);assert.ok(needs.some(n=>n.path==='math.js'&&n.kind==='TODO'));cleanup(d)});

test('mission contract, deterministic assignment, isolated worktree and evidence-gated clear',()=>{const d=tempDir();const repo=join(d,'repo');initGitRepo(repo);const s=createRuntimeStore(join(d,'w.db'));const snap=snapshotRepo(repo);s.registerRepo({repoId:'R',root:repo,branch:snap.branch,head:snap.head,allowedPaths:['math.js'],verificationCommands:['node --test']});s.createAgent({agentId:'K1',birthAt:'x',star:2,status:'IDLE'});s.createAgent({agentId:'K2',birthAt:'x',star:3,status:'BUSY'});s.setAgentProvider('K1','bridge');const m=buildMissionFromNeed(s,{missionId:'M1',repoId:'R',need:detectNeeds(repo)[0]});const selected=selectAgent(s,m);assert.equal(selected.agent_id,'K1');s.assignMission('M1',selected.agent_id);const wt=createMissionWorktree({repoRoot:repo,missionId:'M1',baseHead:snap.head,parentDir:join(d,'worktrees')});writeFileSync(join(wt.path,'math.js'),'export const add = (a,b) => a + b;\n');const files=changedFiles(wt.path);assert.deepEqual(files,['math.js']);assert.equal(readFileSync(join(repo,'math.js'),'utf8').includes('a - b'),true);assert.equal(verifyAllowedPaths(files,['math.js']).ok,true);const receipt=runVerification({cwd:wt.path,command:'node --test'});assert.equal(receipt.exitCode,0);const evid=[s.createEvidence({namespace:'REAL',missionId:'M1',runId:'RUN1',kind:'DIFF',result:'PASS',real:true,payload:{files}}),s.createEvidence({namespace:'REAL',missionId:'M1',runId:'RUN1',kind:'TEST',result:'PASS',real:true,payload:receipt}),s.createEvidence({namespace:'REAL',missionId:'M1',runId:'RUN1',kind:'SCOPE',result:'PASS',real:true,payload:{files}}),s.createEvidence({namespace:'REAL',missionId:'M1',runId:'RUN1',kind:'PROVIDER',result:'PASS',real:true,payload:{providerId:'bridge'}})];assert.equal(clearMissionIfVerified(s,'M1',evid),true);assert.equal(s.getMission('M1').status,'CLEAR');new AgentMind(s).remember('K1',{category:'episodic',content:'Fixed math.js add bug and node --test passed',sourceEvidenceIds:evid,confidence:1});s.close();const s2=createRuntimeStore(join(d,'w.db'));assert.equal(s2.getMission('M1').status,'CLEAR');assert.match(new AgentMind(s2).buildContext('K1','math.js add'),/Fixed math\.js/);s2.close();cleanup(d)});

test('failed verification or scope blocks clear',()=>{const d=tempDir();const s=createRuntimeStore(join(d,'w.db'));s.createMission({missionId:'M',namespace:'REAL',objective:'x',allowedPaths:['src/**'],requiredEvidence:['TEST','SCOPE','DIFF','PROVIDER']});const ids=['DIFF','PROVIDER','SCOPE'].map(k=>s.createEvidence({namespace:'REAL',missionId:'M',runId:'r',kind:k,result:'PASS',real:true}));ids.push(s.createEvidence({namespace:'REAL',missionId:'M',runId:'r',kind:'TEST',result:'FAIL',real:true}));assert.equal(clearMissionIfVerified(s,'M',ids),false);assert.notEqual(s.getMission('M').status,'CLEAR');assert.equal(verifyAllowedPaths(['secret.txt'],['src/**']).ok,false);s.close();cleanup(d)});
